/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in and receive a session cookie */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The logged-in user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change your own password (ends your other sessions) */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database connectivity check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List supported currencies */
        get: operations["listCurrencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the chart of accounts */
        get: operations["listAccounts"];
        put?: never;
        /** Create an account */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountCode}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountCode: components["parameters"]["AccountCode"];
            };
            cookie?: never;
        };
        /** Get one account with its current balance */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename, re-describe or (de)activate an account
         * @description The account `code`, `type` and `currency` are not editable. Inactive accounts
         *     keep their history but cannot receive new postings.
         */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/accounts/{accountCode}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountCode: components["parameters"]["AccountCode"];
            };
            cookie?: never;
        };
        /** Posting history of one account with running balance (in the account's currency) */
        get: operations["getAccountLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journal-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List posted journal entries (newest first) */
        get: operations["listJournalEntries"];
        put?: never;
        /**
         * Post a balanced journal entry
         * @description The header and all lines are written in a single database transaction.
         *     If any line is invalid, or the entry does not balance in every
         *     currency, nothing is saved.
         */
        post: operations["createJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journal-entries/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        /** Get one journal entry with its lines */
        get: operations["getJournalEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journal-entries/{entryId}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post a reversing entry (swaps every debit and credit)
         * @description An entry can be reversed only once, and a reversal cannot itself be reversed.
         */
        post: operations["reverseJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/trial-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debit/credit balance of every account as of a date, totalled per currency */
        get: operations["getTrialBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/balance-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Assets, liabilities and equity as of a date, per currency
         * @description Amounts use each account's natural sign. Revenue minus expenses to
         *     date (not yet closed to an equity account) is reported as
         *     `net_income_cents` and included in total equity, so
         *     assets = liabilities + equity.
         */
        get: operations["getBalanceSheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/income-statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revenue, expenses and net income for a period, per currency */
        get: operations["getIncomeStatement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/general-ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write the General Ledger to a CSV file in the CSV directory
         * @description Columns: `account_code,account_name,account_type,currency,entry_date,
         *     journal_entry_id,line_id,line_number,reference,description,memo,debit,
         *     credit,running_balance`. Rows are grouped by account; the running
         *     balance is per account (debit-positive) in that account's currency.
         *     When `from` is given, each account starts with an "Opening balance" row.
         */
        post: operations["exportGeneralLedger"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List CSV files in the CSV directory */
        get: operations["listCsvFiles"];
        put?: never;
        /**
         * Upload a CSV file into the CSV directory
         * @description The file is stored under its own name, which must match the
         *     `CsvFilename` pattern. Existing files are never overwritten (409).
         *     Max 10 MiB; content must be UTF-8 text (a leading BOM is allowed).
         *     Uploading does not import anything: call `POST /imports/journal-entries`
         *     afterwards.
         */
        post: operations["uploadCsvFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["Filename"];
            };
            cookie?: never;
        };
        /** Download a CSV file */
        get: operations["downloadCsvFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/journal-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import journal entries from a CSV file in the CSV directory
         * @description The whole file is imported in **one database transaction**: if any
         *     entry is invalid, nothing is imported and every problem is reported
         *     with its row number. A file whose exact content (SHA-256) was imported
         *     before is refused with 409, so the same file can't be posted twice.
         *
         *     Format: UTF-8 (a leading BOM is tolerated), comma separated, header
         *     row required, column names case-insensitive and in any order, at most
         *     10 MiB and 50,000 rows.
         *
         *     | column         | required | notes |
         *     |----------------|----------|-------|
         *     | `entry_key`    | yes | Rows with the same key form one journal entry; they must be contiguous |
         *     | `entry_date`   | yes | `YYYY-MM-DD`; may be blank on later rows of an entry |
         *     | `description`  | yes | May be blank on later rows of an entry |
         *     | `account_code` | yes | Existing, active account |
         *     | `debit`        | yes | Decimal, max two decimals (`1234.56`), no signs/separators; blank = 0 |
         *     | `credit`       | yes | Same as debit; exactly one of debit/credit is non-zero |
         *     | `reference`    | no  | May be blank on later rows of an entry |
         *     | `memo`         | no  | Per line |
         *     | `currency`     | no  | `CAD`/`USD`; if given, must match the account's currency |
         *
         *     Example:
         *     ```
         *     entry_key,entry_date,description,account_code,debit,credit
         *     S1,2026-10-01,Cash sale,1000,250.00,
         *     S1,,,4000,,250.00
         *     ```
         */
        post: operations["importJournalEntries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int64
         * @description Non-negative amount in cents.
         */
        Cents: number;
        /**
         * Format: int64
         * @description Signed amount in cents (positive = debit balance, negative = credit balance).
         */
        SignedCents: number;
        /** @enum {string} */
        AccountType: "asset" | "liability" | "equity" | "revenue" | "expense";
        /** @example 1000 */
        AccountCode: string;
        /** @enum {string} */
        Currency: "CAD" | "USD";
        CurrencyInfo: {
            code: components["schemas"]["Currency"];
            /** @example Canadian dollar */
            name: string;
            /** @enum {integer} */
            minor_units: 2;
        };
        CurrencyTotal: {
            currency: components["schemas"]["Currency"];
            amount_cents: components["schemas"]["Cents"];
        };
        CsvFilename: string;
        User: {
            /** @example alice */
            username: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_login_at: string | null;
        };
        LoginRequest: {
            /** @description Case-insensitive */
            username: string;
            /** Format: password */
            password: string;
        };
        PasswordChange: {
            /** Format: password */
            current_password: string;
            /**
             * Format: password
             * @description 10+ characters, at most 72 bytes
             */
            new_password: string;
        };
        ReportLine: {
            account_code: components["schemas"]["AccountCode"];
            account_name: string;
            /** @description Natural-sign balance (a contra balance is negative) */
            amount_cents: components["schemas"]["SignedCents"];
        };
        BalanceSheet: {
            /** Format: date */
            as_of: string;
            currencies: {
                currency: components["schemas"]["Currency"];
                assets: components["schemas"]["ReportLine"][];
                liabilities: components["schemas"]["ReportLine"][];
                equity: components["schemas"]["ReportLine"][];
                /** @description Revenue minus expenses to date, not yet closed to equity */
                net_income_cents: components["schemas"]["SignedCents"];
                total_assets_cents: components["schemas"]["SignedCents"];
                total_liabilities_cents: components["schemas"]["SignedCents"];
                /** @description Equity accounts plus net income */
                total_equity_cents: components["schemas"]["SignedCents"];
                /** @description assets = liabilities + equity */
                balanced: boolean;
            }[];
        };
        IncomeStatement: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            currencies: {
                currency: components["schemas"]["Currency"];
                revenue: components["schemas"]["ReportLine"][];
                expenses: components["schemas"]["ReportLine"][];
                total_revenue_cents: components["schemas"]["SignedCents"];
                total_expenses_cents: components["schemas"]["SignedCents"];
                net_income_cents: components["schemas"]["SignedCents"];
            }[];
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            database: "ok" | "unreachable";
        };
        Error: {
            error: {
                /**
                 * @description Stable machine-readable code
                 * @enum {string}
                 */
                code: "bad_request" | "validation_failed" | "not_found" | "conflict" | "unauthorized" | "forbidden" | "payload_too_large" | "too_many_requests" | "internal_error";
                message: string;
                details?: {
                    /**
                     * @description Offending field, e.g. `lines[1].debit_cents` (JSON) or
                     *     `row 7.account_code` (CSV import)
                     */
                    field?: string;
                    message: string;
                }[];
            };
        };
        Account: {
            code: components["schemas"]["AccountCode"];
            name: string;
            type: components["schemas"]["AccountType"];
            currency: components["schemas"]["Currency"];
            description: string;
            is_active: boolean;
            /** @description Current balance in the account's currency (debit-positive) */
            balance_cents: components["schemas"]["SignedCents"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AccountCreate: {
            code: components["schemas"]["AccountCode"];
            /** @example Bank CAD */
            name: string;
            type: components["schemas"]["AccountType"];
            currency: components["schemas"]["Currency"];
            /** @default  */
            description: string;
        };
        AccountUpdate: {
            name?: string;
            description?: string;
            is_active?: boolean;
        };
        /**
         * @description Exactly one of debit_cents / credit_cents must be > 0. The amount is
         *     in the account's currency.
         */
        JournalLineCreate: {
            account_code: components["schemas"]["AccountCode"];
            debit_cents: components["schemas"]["Cents"];
            credit_cents: components["schemas"]["Cents"];
            /** @default  */
            memo: string;
        };
        JournalEntryCreate: {
            /** Format: date */
            entry_date: string;
            description: string;
            /** @default  */
            reference: string;
            lines: components["schemas"]["JournalLineCreate"][];
        };
        JournalLine: {
            /** Format: int64 */
            id: number;
            line_number: number;
            account_code: components["schemas"]["AccountCode"];
            account_name: string;
            currency: components["schemas"]["Currency"];
            debit_cents: components["schemas"]["Cents"];
            credit_cents: components["schemas"]["Cents"];
            memo: string;
        };
        JournalEntry: {
            /** Format: int64 */
            id: number;
            /** Format: date */
            entry_date: string;
            description: string;
            reference: string;
            /**
             * Format: int64
             * @description Set when this entry reverses another entry
             */
            reverses_id: number | null;
            /**
             * Format: int64
             * @description Set when another entry reverses this one
             */
            reversed_by_id: number | null;
            /**
             * Format: int64
             * @description Set when the entry was created by a CSV import
             */
            import_id: number | null;
            /** @description Username of the person who posted the entry */
            created_by: string | null;
            /** Format: date-time */
            posted_at: string;
            /** @description Per-currency sum of debits (always equal to the sum of credits), ordered by currency */
            totals: components["schemas"]["CurrencyTotal"][];
            lines: components["schemas"]["JournalLine"][];
        };
        ReverseRequest: {
            /**
             * Format: date
             * @description Date of the reversing entry (default today)
             */
            entry_date?: string;
            /** @description Default "Reversal of entry */
            description?: string;
        };
        AccountLedger: {
            account: components["schemas"]["Account"];
            opening_balance_cents: components["schemas"]["SignedCents"];
            closing_balance_cents: components["schemas"]["SignedCents"];
            lines: {
                /** Format: int64 */
                journal_entry_id: number;
                /** Format: int64 */
                line_id: number;
                /** Format: date */
                entry_date: string;
                description: string;
                reference?: string;
                memo: string;
                debit_cents: components["schemas"]["Cents"];
                credit_cents: components["schemas"]["Cents"];
                running_balance_cents: components["schemas"]["SignedCents"];
            }[];
        };
        TrialBalance: {
            /** Format: date */
            as_of: string;
            /** @description Ordered by currency, then account code */
            rows: {
                account_code: components["schemas"]["AccountCode"];
                account_name: string;
                account_type: components["schemas"]["AccountType"];
                currency: components["schemas"]["Currency"];
                debit_cents: components["schemas"]["Cents"];
                credit_cents: components["schemas"]["Cents"];
            }[];
            /** @description One row per currency; debits always equal credits */
            totals: {
                currency: components["schemas"]["Currency"];
                debit_cents: components["schemas"]["Cents"];
                credit_cents: components["schemas"]["Cents"];
            }[];
        };
        ExportRequest: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            /** @description Only accounts in this currency (default all) */
            currency?: components["schemas"]["Currency"];
        };
        CsvFile: {
            filename: components["schemas"]["CsvFilename"];
            /** Format: int64 */
            size_bytes: number;
            /** Format: date-time */
            modified_at: string;
            /** @description Data rows written (export responses only) */
            row_count?: number;
        };
        ImportRequest: {
            filename: components["schemas"]["CsvFilename"];
        };
        ImportResult: {
            /** Format: int64 */
            import_id: number;
            filename: string;
            sha256: string;
            entries_imported: number;
            lines_imported: number;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        AccountCode: components["schemas"]["AccountCode"];
        EntryId: number;
        Filename: components["schemas"]["CsvFilename"];
        /** @description Inclusive start date */
        From: string;
        /** @description Inclusive end date */
        To: string;
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in; `Set-Cookie` carries the session */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out (cookie cleared) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service and database are reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listCurrencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Currencies ordered by code */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CurrencyInfo"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts ordered by code */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Account"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountCode: components["parameters"]["AccountCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountCode: components["parameters"]["AccountCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getAccountLedger: {
        parameters: {
            query?: {
                /** @description Inclusive start date */
                from?: components["parameters"]["From"];
                /** @description Inclusive end date */
                to?: components["parameters"]["To"];
            };
            header?: never;
            path: {
                accountCode: components["parameters"]["AccountCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ledger lines ordered by date, entry id, line number */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountLedger"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    listJournalEntries: {
        parameters: {
            query?: {
                /** @description Inclusive start date */
                from?: components["parameters"]["From"];
                /** @description Inclusive end date */
                to?: components["parameters"]["To"];
                /** @description Only entries with at least one line on this account */
                account_code?: components["schemas"]["AccountCode"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of journal entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["JournalEntry"][];
                        limit: number;
                        offset: number;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createJournalEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "entry_date": "2026-10-01",
                 *       "description": "Office supplies paid in cash",
                 *       "reference": "RCPT-0042",
                 *       "lines": [
                 *         {
                 *           "account_code": "6100",
                 *           "debit_cents": 4599,
                 *           "credit_cents": 0,
                 *           "memo": "Printer paper"
                 *         },
                 *         {
                 *           "account_code": "1000",
                 *           "debit_cents": 0,
                 *           "credit_cents": 4599
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["JournalEntryCreate"];
            };
        };
        responses: {
            /** @description Entry posted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            422: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getJournalEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The journal entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    reverseJournalEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReverseRequest"];
            };
        };
        responses: {
            /** @description Reversing entry posted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getTrialBalance: {
        parameters: {
            query?: {
                /** @description Include entries dated on or before this day (default today) */
                as_of?: string;
                /** @description Only accounts in this currency */
                currency?: components["schemas"]["Currency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trial balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrialBalance"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getBalanceSheet: {
        parameters: {
            query?: {
                /** @description Include entries dated on or before this day (default today) */
                as_of?: string;
                currency?: components["schemas"]["Currency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Balance sheet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceSheet"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getIncomeStatement: {
        parameters: {
            query?: {
                /** @description Inclusive start date (default January 1 of the `to` year) */
                from?: string;
                /** @description Inclusive end date (default today) */
                to?: string;
                currency?: components["schemas"]["Currency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Income statement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeStatement"];
                };
            };
            422: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    exportGeneralLedger: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description File written */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsvFile"];
                };
            };
            422: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    listCsvFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Files, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CsvFile"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    uploadCsvFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description File stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsvFile"];
                };
            };
            409: components["responses"]["Error"];
            413: components["responses"]["Error"];
            422: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    downloadCsvFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["Filename"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    importJournalEntries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description All entries imported */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
}
